### ISSUE TITLE
Any plans to add DTLS support?

### ISSUE THREAD

**Issue by therealprof** [Synss/python-mbedtls#7] opened 2018-02-14 12:14 UTC
It would be if other parts, e.g. the really great DTLS support in mbedTLS, were also supported, even if just partially. Any plans to add a wrapper?

**Comment by Synss** [comment] 2018-02-14 16:03
I can give it a try and see how far I get... non-blocking IO even [seems to be possible](https://tls.mbed.org/kb/how-to/dtls-tutorial) and would be really interesting.

**Comment by therealprof** [comment] 2018-02-14 16:10
Yes, absolutely. mbedTLS is used in quite a lot of embedded devices with OSes like Zephyr  (https://www.zephyrproject.org/) or ARMs own mbed OS (https://www.mbed.com/en/) for DTLS, even as a server.

If find mbedTLS to be quite a bit better than OpenSSL/LibreSSL in many regards but unfortunately the few DTLS implementations available for Python all rely on OpenSSL. 👎

**Comment by Synss** [comment] 2018-08-08 19:05
Just to keep you updated, I am working on TLS now and for some time already. Handshake is working as well as send/recv on Python 3. On Python 2.7, handshake is working but the encrypted data do not seem to go over the socket. I do not think that certificate validation works.

Still, I am making progress.

Once TLS works reliably, I will go for DTLS.

I hope to be done by the end of the year.

**Comment by Synss** [comment] 2019-01-11 20:38
Hi @jarednm, TLS took longer than I thought. Recently, I have been working on creating wheels to distribute mbedtls (the C library) with mine so that ```pip install python-mbedtls``` just works. The recent 0.14 comes with 64-bit manylinux wheels.

Now DTLS is next on my list.

**Comment by Synss** [comment] 2019-02-04 20:11
I have now witnessed a complete client-server DTLS handshake. Communication fails thereafter and DTLS is not usable but there is progress.

**Comment by Synss** [comment] 2019-02-09 20:58
Now I have a working DTLS echo server. I still have to clean up and some socket-related things are not entirely clean to me. But the working echo server shows that most of the crypto (and most of the socket work) is in place.

**Comment by Synss** [comment] 2019-02-16 19:29
One week after, I have basic DTLS fully working. Basic now means no cookie, no certificate validation but handshake works reliably and a server is able to work with several clients. Would that be good enough to somebody, I could make a release. Otherwise, I will release after cookie and certificate validation actually works—That could be a few more weeks.

**Comment by Synss** [comment] 2019-02-23 11:18
As far as I can see, DTLS is fully working now. However, the tests with TLSVersion.TLSv1 do not pass anymore. I will investigate. I may nevertheless make a release with DTLS in and TLSv1 disabled in the meantime. The tests for TLSv1_1 and TLSv1_2 pass so TLS still works in principle.

**Comment by Synss** [comment] 2019-03-15 17:28
DTLS is in 0.15.0 that I have just released. The tests for TLSv1 remain disabled: I do not understand what the problem is but I do not want to delay DTLS anymore.

Feedback is always welcome! But for now, I will close this ticket.

**Closed by Synss** 2019-03-15 17:28 UTC
